services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_Password123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: CifraShop.API/Dockerfile
    ports:
      - "5000:8086"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8086
      - ConnectionStrings__DefaultConnection=Server=db;Database=CifraShopDb;User Id=sa;Password=Your_strong_Password123;TrustServerCertificate=True;
      - SmtpSettings__Host=mailhog
      - SmtpSettings__Port=1025
      - SmtpSettings__Username=
      - SmtpSettings__Password=
      - SmtpSettings__FromEmail=noreply@cifrashop.com
      - SmtpSettings__FromName=CifraShop
    volumes:
      - api-images:/app/wwwroot/images
    depends_on:
      - db
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  sqlserver-data:
  api-images: