<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <ProjectReference Include="..\CifraShoop.Data\CifraShop.Data.csproj" />
	  <ProjectReference Include="..\CifraShop.Domain\CifraShop.Domain.csproj" />
  </ItemGroup>

</Project>
