<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\Tests\**" />
    <Content Remove="Components\Tests\**" />
    <EmbeddedResource Remove="Components\Tests\**" />
    <None Remove="Components\Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CifraShop.Contracts\CifraShop.Contracts.csproj" />
    <ProjectReference Include="..\..\CifraShop.Domain\CifraShop.Domain.csproj" />
    <ProjectReference Include="..\..\CifraShop.Dto\CifraShop.Dto.csproj" />
    <ProjectReference Include="..\CifraShop.Client\CifraShop.Client.csproj" />
	  <ProjectReference Include="..\..\CIfraShop.Services\CIfraShop.Services.csproj" />
	  <ProjectReference Include="..\..\CifraShoop.Data\CifraShop.Data.csproj" />
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
